version: '3.4'

networks:
  integration-test:

services:
  expense_tracking:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    volumes:
      - $PWD:/go/src/expense
    depends_on:
      - postgresDB
    networks:
      - integration-test
  postgresDB:
    image: postgres:12.12
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: expenseDB
    restart: on-failure
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    networks:
      - integration-test
    